.TH  "password_manager_selinux"  "8"  "23-01-21" "password_manager" "SELinux Policy password_manager"
.SH "NAME"
password_manager_selinux \- Security Enhanced Linux Policy for the password_manager processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the password_manager processes via flexible mandatory access control.

The password_manager processes execute with the password_manager_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep password_manager_t


.SH "ENTRYPOINTS"

The password_manager_t SELinux type can be entered via the \fBpassword_manager_exec_t\fP file type.

The default entrypoint paths for the password_manager_t domain are the following:

/usr/local/bin/password_manager
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux password_manager policy is very flexible allowing users to setup their password_manager processes in as secure a method as possible.
.PP
The following process types are defined for password_manager:

.EX
.B password_manager_t
.EE
.PP
Note:
.B semanage permissive -a password_manager_t
can be used to make the process type password_manager_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  password_manager policy is extremely flexible and has several booleans that allow you to manipulate the policy and run password_manager with the tightest access possible.


.PP
If you want to determine whether confined applications can use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux password_manager policy is very flexible allowing users to setup their password_manager processes in as secure a method as possible.
.PP

.PP
.B STANDARD FILE CONTEXT

SELinux defines the file context types for the password_manager, if you wanted to
store files with these types in a diffent paths, you need to execute the semanage command to sepecify alternate labeling and then use restorecon to put the labels on disk.

.B semanage fcontext -a -t password_manager_exec_t '/srv/password_manager/content(/.*)?'
.br
.B restorecon -R -v /srv/mypassword_manager_content

Note: SELinux often uses regular expressions to specify labels that match multiple files.

.I The following file types are defined for password_manager:


.EX
.PP
.B password_manager_exec_t
.EE

- Set files with the password_manager_exec_t type, if you want to transition an executable to the password_manager_t domain.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage".

.SH "SEE ALSO"
selinux(8), password_manager(8), semanage(8), restorecon(8), chcon(1), sepolicy(8), setsebool(8)